### ISSUE TITLE
[security-cdi-keycloak] Always unauthorized when running in Docker containers

### ISSUE THREAD

**Issue by CPIJ** [kumuluz/kumuluzee-samples#24]
Hi,

I'm following [this guide]( https://github.com/kumuluz/kumuluzee-samples/tree/master/kumuluzee-security-cdi-keycloak) to test KumuluzEE and Keycloak. When I run the `CustomerApplication` on my own machine everything is fine. But when I try to move it to a Docker container I keep getting `401 Unauthorized` when trying to access `/v1/customers` or any other endpoint.

Here's my docker-compose file

```yaml
version: '3'

services:
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8082:8080

  app:
    image: maven:3.6.0-alpine
    command: java -jar /usr/src/app/target/kumuluzee-security-cdi-keycloak-3.5.0-SNAPSHOT.jar
    volumes:
      - ./target:/usr/src/app/target
    ports:
      - 8080:8080
```

And here's my kumuluz config.

```yaml
kumuluzee:
  name: customer-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  security:
    keycloak:
      json: '{
               "realm": "customers-realm",
               "bearer-only": true,
               "auth-server-url": "http://keycloak:8080/auth",
               "ssl-required": "external",
               "resource": "customers-api",
               "confidential-port": 0
             }'
```

As you see, I tried using `keycloak` as the hostname, sadly this did not work. 

When I ran this configuration I got the following exception: `org.keycloak.adapters.rotation.AdapterTokenVerifier -- Didn't find publicKey for kid: <kid>`. So, I added `"realm-public-key": "<pubk>"` to the config.

The error message is gone, but sadly I still get `401 Unauthorized`. I'm fairly new to Keycloak, so maybe I'm making a simple mistake.. either way, I hope you can provide some help :)

Thanks!

**Comment by osbeorn** [comment]
I'm fairly confident that the token issuer URL doesn't match the realm URL.
Try using the following docker-compose.yml:
```yml
version: '3'

services:
  keycloak:
    image: jboss/keycloak:5.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HOSTNAME: keycloak
    ports:
      - 8080:8080

  app:
    image: maven:3.6.0-alpine
    container_name: app
    command: java -agentlib:jdwp=transport=dt_socket,server=y,address=8888 -jar /usr/src/app/target/kumuluzee-security-cdi-keycloak-3.5.0-SNAPSHOT.jar
    volumes:
      - ./target:/usr/src/app/target
    links:
      - keycloak
    ports:
      - 8081:8080
      - 8888:8888
    depends_on:
      - keycloak
```

You will have to add `keycloak` mapping to your hosts file in order for you to access `keycloak` outside docker.
